### ISSUE TITLE
TODO list for PR-6 dev

### ISSUE THREAD

**Issue by Bogdan-G** [Bogdan-G/Burner-ModPack-Lite#8]
Один из списков что сделать. 

~~25-01-16 3-32: Этап пройден, отделяю часть сообщения.~~

<hr>

~~Список до 25-01-16 3-32:~~ ой я продолжил пихать в старый список.
01.04.17 2-28: добавлена информация, время взято когда вбивал его ну мб еще строчка с датой. То что добавилось - не в хронологическом порядке. И часть добавленного мб отходит от темы этого TODO.

<hr>

- [ ] отредактировать настройки распостранения (поощрения?) огня вводимые модом NatureOverhaul
- [x] в тропикрафте выкл прыжки рыбы-сабли, т.к. вызывало _стоппинг_ ее ИИ или рыба вне воды висела, мб код недописан или что то еще
- [x] в моде ItemPhysics добавлена конфиг опция восставнавливающая фичу сервера стакать блоки, так же кол-во обновновлений EntityItem снижено где то в 2 раза
- [x] в EBXL уменьшено кол-во getBlock чеков для 2х2 деревьев при генерации
- [x] в MFR урезана часота генерации резиновых деревьев, часть boolean[] (в т.ч. более чем одномерные) переделаны на BitSet
- [x] в BC изменялись время сейва в чанк (вроде то что с роботами) и частоты отправки пакетов
- [x] в TiC время горения/траты изменено
- [x] руды части модов и в т.ч. часть ванила блоков и руд, а так же блоки UBC требуют для выкапывания минимум уровень железной кирки
- [x] ванильный крафт верстака был удален
- [x] в TwilightForest были апнуты монстры + немношк рандомное им хп разброс
- [x] при исп системы кэша MFF было обнаружено что Waila часто туда обращается, это было исправлено
- [x] ускорения генерации в UBC
- [x] были убраны лишние реалоады текстур в конце запуска модом DragonAPI, так же часть этого мода была почищена
- [ ] была сделана, но не до конца _довстроена/доделана под др_ система кэширования на диск в MFF
- [x] ускорение стадии PostInit в гречке, 01.04.17 был откат той правки, потом др варианты, рецептов не много хоть и тратит кучу времени, добавлены конфиг опции, тоже не слито в репо
- [ ] проблема ТЕ-рендера в моде GraveStone, сажает фпс клиента, устройчив к оптифайну/ФК, вероятно требуется переписвание рендерера, это выходит за рамки багфиксов мелких-средних, не известно будет ли исправлено, 01.04.17 перетащил из ванила класса(ов) 1 или неск методов что подняло фпс на 5 где то в центре возле огней
- [x] добавлен в часть модов и сервере XSTR
- [x] уменьшить кол-во вызовов обновлений блоков/тиков модом NatureOverhaul
- [x] исправить NPE на стороне MrCrayfishFurnitureMod с Waila (спасибо @Fewizz -у)
- [x] бубен с tps сервера N2
- [x] бубен с tps сервера
- [x] ~~исправить не сохраняющийся при смерти инвентарь в могилки из GraveStone~~ (wontfix?)
- [x] исправить краш с модом MFQM на стороне KC(проблема в том что при попадании в трясину клиент крашит из-за несоотвествия типов) (спасибо @Fewizz -у)
- [x] исправить баг сохранения статусов при смерти в моде EnviroMine на стороне KC(спасибо @Prototik -у)
- [x] откатить версию ExtraCells, причина: не работает на стороне КС
- [x] ~~совместимость на стороне KC с модом DragonAPI v10~~ (откат на более старую версию)
- [x] совместимость на стороне KC с модом NatureOverhaul ~~(откат на более старую версию)~~ - исправлено на стороне KC
- [x] выключить часть в конфигах модов настройки совместимости с модами которых нет в сборке
- [x] О_о
- [x] залить бета билд в декабре
- [x] добавить генерацию данжей из CQ в 7 дименсион (?)
- [x] настроить все ID биомов (я не уверен на 100%)
- [x] ~~исправить баг генерации в БоПе модом большие деревья (баг есть, но я не смог его воспроизвести)~~ (я не вижу баг)
- [x] посмотреть можно ли ускорить генерацию мира
- [ ] посмотреть можно ли ускорить загрузку игры (бесполезно, вычеркиваем), 01.04.17 путем ковыряния модов возможно, например грега, сама ваниль - ресурслоадер пинать к примеру
- [x] ~~решить проблему с limit BiomeID (временно убран мод TragicMC2 и иные др моды доб биомы, ибо лимит исчерпан)~~
- [x] решить проблему с limit DataWater (спасибо @Fewizz -у)
- [x] решить проблему с MFQM (спасибо @Fewizz -у)
- [x] облегчить генерацию Руд
- [x] облегчить генерацию надземных объектов
- [x] решить проблему с biome decoration (временно уменьшение генерации частоты и кол-ва всего подземного мира еще больше), 01.04.17 я из FFoKC притащил фрагмент где бросание исключения нет, а в др месте просто вместого исключения возвращает блок воздуха
- [x] убрать требование модов к высокой версии Forge т.к. используется кастомная версия MFFB (MinecraftForge Fork for BMPL) с др нумерацией -> пока что сделано
  <hr>

**Уменьшить утечки памяти**
- [x] увеличить выделяемую память
- [x] обновить версии модов (в процессе их выхода)
- [x] ~~исправить NPE (?)~~ (не ясно, оно само ушло?)

**Поднять фпс**
- [x] правка конфигов options/optionsof под новый билд
- [x] изменять параметры ява-машины (в процессе)
- [x] подредактировать код, но выяснилось что не эффективно
- [x] докрутить что-нибудь

**Облегчить генерацию гречки**
- [x] убрать генерацию smallOre
- [x] сделать меньше mixOreVein
- [x] сделать генерации более редкой через код мода (пока что феил), сделано, но коммит на 01.04.17 не слит в репо, тупо рандом генератор по аналогии как в NatureOverhaul вставил

**Comment by Bogdan-G** [comment]
#1

**Comment by Bogdan-G** [comment]
да увы баги есть, не критичные, но мешать могут

**Comment by Bogdan-G** [comment]
#закрыть галочек

**Comment by Bogdan-G** [comment]
ой а это не много не обновлял

**Comment by Bogdan-G** [comment]
список поехал, 9мес назад редачил пишет, и хз что они "сломали".
починил.
